### ISSUE TITLE
"Couldn’t install plugin."

### ISSUE THREAD

**Issue by bartrylant** [verbb/Events#1]
I've installed Events with composer. It appears on my plugins page in the control panel, but when I click on "install" there, I get a red bar on top of the screen saying "Couldn’t install plugin."

PHP version 7.2.10
Craft CMS 3.1.23
Craft Commerce 2.1.3.1
Events 1.0.0

**Comment by mikestecker** [comment]
Same issue.

PHP 7.2.16
Craft 3.1.24
Commerce 2.1.3.1
Events 1.0

Here are the relevant parts of my log:
```
2019-04-23 16:22:21 [-][1][-][trace][craft\web\Application::_processActionRequest] Route requested: 'plugins/install-plugin'
2019-04-23 16:22:21 [-][1][-][trace][yii\base\Controller::runAction] Route to run: plugins/install-plugin
2019-04-23 16:22:21 [-][1][-][trace][yii\base\InlineAction::runWithParams] Running action: craft\controllers\PluginsController::actionInstallPlugin()
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::query] SELECT `id`, `handle`, `version`, `schemaVersion`, `licenseKeyStatus`, `installDate`, `licensedEdition`
FROM `plugins`
WHERE `handle`='events'
LIMIT 1
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::query] SELECT `id`, `handle`, `version`, `schemaVersion`, `licenseKeyStatus`, `installDate`, `licensedEdition`
FROM `plugins`
WHERE `handle`='events'
LIMIT 1
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::query] SELECT `id`, `handle`, `version`, `schemaVersion`, `licenseKeyStatus`, `installDate`, `licensedEdition`
FROM `plugins`
WHERE `handle`='events'
LIMIT 1
2019-04-23 16:22:21 [-][1][-][trace][yii\db\Transaction::begin] Begin transaction
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::query] SHOW FULL COLUMNS FROM `plugins`
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::query] SHOW FULL COLUMNS FROM `plugins`
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::query] SHOW FULL COLUMNS FROM `plugins`
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::query] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'plugins' AND kcu.table_name = 'plugins'
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::query] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'plugins' AND kcu.table_name = 'plugins'
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::query] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'plugins' AND kcu.table_name = 'plugins'
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::query] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name,
    rc.UPDATE_RULE,
    rc.DELETE_RULE
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'plugins' AND kcu.table_name = 'plugins'
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::query] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name,
    rc.UPDATE_RULE,
    rc.DELETE_RULE
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'plugins' AND kcu.table_name = 'plugins'
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::query] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name,
    rc.UPDATE_RULE,
    rc.DELETE_RULE
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'plugins' AND kcu.table_name = 'plugins'
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] INSERT INTO `plugins` (`handle`, `version`, `schemaVersion`, `installDate`, `dateCreated`, `dateUpdated`, `uid`) VALUES ('events', '1.0.0', '1.0.0', '2019-04-23 20:22:21', '2019-04-23 20:22:21', '2019-04-23 20:22:21', '70e08dd4-7493-4063-9ec9-3d923b529cf2')
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] INSERT INTO `plugins` (`handle`, `version`, `schemaVersion`, `installDate`, `dateCreated`, `dateUpdated`, `uid`) VALUES ('events', '1.0.0', '1.0.0', '2019-04-23 20:22:21', '2019-04-23 20:22:21', '2019-04-23 20:22:21', '70e08dd4-7493-4063-9ec9-3d923b529cf2')
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] INSERT INTO `plugins` (`handle`, `version`, `schemaVersion`, `installDate`, `dateCreated`, `dateUpdated`, `uid`) VALUES ('events', '1.0.0', '1.0.0', '2019-04-23 20:22:21', '2019-04-23 20:22:21', '2019-04-23 20:22:21', '70e08dd4-7493-4063-9ec9-3d923b529cf2')
2019-04-23 16:22:21 [-][1][-][info][craft\db\MigrationManager::migrateUp] Applying Install
2019-04-23 16:22:21 [-][1][-][trace][yii\db\Transaction::begin] Set savepoint 1
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] SAVEPOINT LEVEL1
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] SAVEPOINT LEVEL1
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] SAVEPOINT LEVEL1
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] CREATE TABLE `events_events` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`typeId` int(11),
	`allDay` tinyint(1),
	`capacity` int(11),
	`startDate` datetime,
	`endDate` datetime,
	`postDate` datetime,
	`expiryDate` datetime,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] CREATE TABLE `events_events` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`typeId` int(11),
	`allDay` tinyint(1),
	`capacity` int(11),
	`startDate` datetime,
	`endDate` datetime,
	`postDate` datetime,
	`expiryDate` datetime,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] CREATE TABLE `events_events` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`typeId` int(11),
	`allDay` tinyint(1),
	`capacity` int(11),
	`startDate` datetime,
	`endDate` datetime,
	`postDate` datetime,
	`expiryDate` datetime,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] CREATE TABLE `events_eventtypes` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`fieldLayoutId` int(11),
	`name` varchar(255) NOT NULL,
	`handle` varchar(255) NOT NULL,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] CREATE TABLE `events_eventtypes` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`fieldLayoutId` int(11),
	`name` varchar(255) NOT NULL,
	`handle` varchar(255) NOT NULL,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] CREATE TABLE `events_eventtypes` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`fieldLayoutId` int(11),
	`name` varchar(255) NOT NULL,
	`handle` varchar(255) NOT NULL,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] CREATE TABLE `events_eventtypes_sites` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`eventTypeId` int(11) NOT NULL,
	`siteId` int(11) NOT NULL,
	`uriFormat` text,
	`template` varchar(500),
	`hasUrls` tinyint(1),
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] CREATE TABLE `events_eventtypes_sites` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`eventTypeId` int(11) NOT NULL,
	`siteId` int(11) NOT NULL,
	`uriFormat` text,
	`template` varchar(500),
	`hasUrls` tinyint(1),
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] CREATE TABLE `events_eventtypes_sites` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`eventTypeId` int(11) NOT NULL,
	`siteId` int(11) NOT NULL,
	`uriFormat` text,
	`template` varchar(500),
	`hasUrls` tinyint(1),
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] CREATE TABLE `events_tickets` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`eventId` int(11),
	`typeId` int(11),
	`sku` varchar(255) NOT NULL,
	`quantity` int(11),
	`price` decimal(14,4) NOT NULL,
	`availableFrom` datetime,
	`availableTo` datetime,
	`sortOrder` int(11),
	`deletedWithEvent` int(11) NULL DEFAULT NULL,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] CREATE TABLE `events_tickets` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`eventId` int(11),
	`typeId` int(11),
	`sku` varchar(255) NOT NULL,
	`quantity` int(11),
	`price` decimal(14,4) NOT NULL,
	`availableFrom` datetime,
	`availableTo` datetime,
	`sortOrder` int(11),
	`deletedWithEvent` int(11) NULL DEFAULT NULL,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] CREATE TABLE `events_tickets` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`eventId` int(11),
	`typeId` int(11),
	`sku` varchar(255) NOT NULL,
	`quantity` int(11),
	`price` decimal(14,4) NOT NULL,
	`availableFrom` datetime,
	`availableTo` datetime,
	`sortOrder` int(11),
	`deletedWithEvent` int(11) NULL DEFAULT NULL,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] CREATE TABLE `events_tickettypes` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`taxCategoryId` int(11) NOT NULL,
	`shippingCategoryId` int(11) NOT NULL,
	`fieldLayoutId` int(11),
	`handle` varchar(255) NOT NULL,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] CREATE TABLE `events_tickettypes` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`taxCategoryId` int(11) NOT NULL,
	`shippingCategoryId` int(11) NOT NULL,
	`fieldLayoutId` int(11),
	`handle` varchar(255) NOT NULL,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] CREATE TABLE `events_tickettypes` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`taxCategoryId` int(11) NOT NULL,
	`shippingCategoryId` int(11) NOT NULL,
	`fieldLayoutId` int(11),
	`handle` varchar(255) NOT NULL,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] CREATE TABLE `events_purchasedtickets` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`eventId` int(11),
	`ticketId` int(11),
	`orderId` int(11),
	`lineItemId` int(11),
	`ticketSku` varchar(255),
	`checkedIn` tinyint(1),
	`checkedInDate` datetime,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] CREATE TABLE `events_purchasedtickets` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`eventId` int(11),
	`ticketId` int(11),
	`orderId` int(11),
	`lineItemId` int(11),
	`ticketSku` varchar(255),
	`checkedIn` tinyint(1),
	`checkedInDate` datetime,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] CREATE TABLE `events_purchasedtickets` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`eventId` int(11),
	`ticketId` int(11),
	`orderId` int(11),
	`lineItemId` int(11),
	`ticketSku` varchar(255),
	`checkedIn` tinyint(1),
	`checkedInDate` datetime,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] ALTER TABLE `events_events` ADD INDEX `events_events_typeId_idx` (`typeId`)
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] ALTER TABLE `events_events` ADD INDEX `events_events_typeId_idx` (`typeId`)
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] ALTER TABLE `events_events` ADD INDEX `events_events_typeId_idx` (`typeId`)
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] ALTER TABLE `events_eventtypes` ADD UNIQUE INDEX `events_eventtypes_handle_unq_idx` (`handle`)
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] ALTER TABLE `events_eventtypes` ADD UNIQUE INDEX `events_eventtypes_handle_unq_idx` (`handle`)
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] ALTER TABLE `events_eventtypes` ADD UNIQUE INDEX `events_eventtypes_handle_unq_idx` (`handle`)
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] ALTER TABLE `events_eventtypes` ADD INDEX `events_eventtypes_fieldLayoutId_idx` (`fieldLayoutId`)
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] ALTER TABLE `events_eventtypes` ADD INDEX `events_eventtypes_fieldLayoutId_idx` (`fieldLayoutId`)
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] ALTER TABLE `events_eventtypes` ADD INDEX `events_eventtypes_fieldLayoutId_idx` (`fieldLayoutId`)
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] ALTER TABLE `events_eventtypes_sites` ADD UNIQUE INDEX `events_eventtypes_sites_eventTypeId_siteId_unq_idx` (`eventTypeId`, `siteId`)
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] ALTER TABLE `events_eventtypes_sites` ADD UNIQUE INDEX `events_eventtypes_sites_eventTypeId_siteId_unq_idx` (`eventTypeId`, `siteId`)
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] ALTER TABLE `events_eventtypes_sites` ADD UNIQUE INDEX `events_eventtypes_sites_eventTypeId_siteId_unq_idx` (`eventTypeId`, `siteId`)
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] ALTER TABLE `events_eventtypes_sites` ADD INDEX `events_eventtypes_sites_siteId_idx` (`siteId`)
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] ALTER TABLE `events_eventtypes_sites` ADD INDEX `events_eventtypes_sites_siteId_idx` (`siteId`)
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] ALTER TABLE `events_eventtypes_sites` ADD INDEX `events_eventtypes_sites_siteId_idx` (`siteId`)
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] ALTER TABLE `events_purchasedtickets` ADD INDEX `events_purchasedtickets_eventId_idx` (`eventId`)
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] ALTER TABLE `events_purchasedtickets` ADD INDEX `events_purchasedtickets_eventId_idx` (`eventId`)
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] ALTER TABLE `events_purchasedtickets` ADD INDEX `events_purchasedtickets_eventId_idx` (`eventId`)
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] ALTER TABLE `events_purchasedtickets` ADD INDEX `events_purchasedtickets_ticketId_idx` (`ticketId`)
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] ALTER TABLE `events_purchasedtickets` ADD INDEX `events_purchasedtickets_ticketId_idx` (`ticketId`)
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] ALTER TABLE `events_purchasedtickets` ADD INDEX `events_purchasedtickets_ticketId_idx` (`ticketId`)
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] ALTER TABLE `events_purchasedtickets` ADD INDEX `events_purchasedtickets_orderId_idx` (`orderId`)
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] ALTER TABLE `events_purchasedtickets` ADD INDEX `events_purchasedtickets_orderId_idx` (`orderId`)
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] ALTER TABLE `events_purchasedtickets` ADD INDEX `events_purchasedtickets_orderId_idx` (`orderId`)
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] ALTER TABLE `events_purchasedtickets` ADD INDEX `events_purchasedtickets_lineItemId_idx` (`lineItemId`)
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] ALTER TABLE `events_purchasedtickets` ADD INDEX `events_purchasedtickets_lineItemId_idx` (`lineItemId`)
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] ALTER TABLE `events_purchasedtickets` ADD INDEX `events_purchasedtickets_lineItemId_idx` (`lineItemId`)
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] ALTER TABLE `events_tickets` ADD UNIQUE INDEX `events_tickets_sku_unq_idx` (`sku`)
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] ALTER TABLE `events_tickets` ADD UNIQUE INDEX `events_tickets_sku_unq_idx` (`sku`)
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] ALTER TABLE `events_tickets` ADD UNIQUE INDEX `events_tickets_sku_unq_idx` (`sku`)
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] ALTER TABLE `events_tickets` ADD INDEX `events_tickets_eventId_idx` (`eventId`)
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] ALTER TABLE `events_tickets` ADD INDEX `events_tickets_eventId_idx` (`eventId`)
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] ALTER TABLE `events_tickets` ADD INDEX `events_tickets_eventId_idx` (`eventId`)
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] ALTER TABLE `events_tickets` ADD INDEX `events_tickets_ticketTypeId_idx` (`ticketTypeId`)
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] ALTER TABLE `events_tickets` ADD INDEX `events_tickets_ticketTypeId_idx` (`ticketTypeId`)
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] ALTER TABLE `events_tickets` ADD INDEX `events_tickets_ticketTypeId_idx` (`ticketTypeId`)
2019-04-23 16:22:21 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back to savepoint 1
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2019-04-23 16:22:21 [-][1][-][warning][craft\db\mysql\Schema::rollBackSavepoint] Tried to roll back a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: ROLLBACK TO SAVEPOINT LEVEL1
2019-04-23 16:22:21 [-][1][-][error][craft\db\MigrationManager::migrateUp] Failed to apply Install (time: 0.045s). Output:
    > create table {{%events_events}} ... done (time: 0.008s)
    > create table {{%events_eventtypes}} ... done (time: 0.005s)
    > create table {{%events_eventtypes_sites}} ... done (time: 0.004s)
    > create table {{%events_tickets}} ... done (time: 0.004s)
    > create table {{%events_tickettypes}} ... done (time: 0.003s)
    > create table {{%events_purchasedtickets}} ... done (time: 0.004s)
    > create index events_events_typeId_idx on {{%events_events}} (typeId) ... done (time: 0.001s)
    > create unique index events_eventtypes_handle_unq_idx on {{%events_eventtypes}} (handle) ... done (time: 0.001s)
    > create index events_eventtypes_fieldLayoutId_idx on {{%events_eventtypes}} (fieldLayoutId) ... done (time: 0.001s)
    > create unique index events_eventtypes_sites_eventTypeId_siteId_unq_idx on {{%events_eventtypes_sites}} (eventTypeId,siteId) ... done (time: 0.001s)
    > create index events_eventtypes_sites_siteId_idx on {{%events_eventtypes_sites}} (siteId) ... done (time: 0.001s)
    > create index events_purchasedtickets_eventId_idx on {{%events_purchasedtickets}} (eventId) ... done (time: 0.002s)
    > create index events_purchasedtickets_ticketId_idx on {{%events_purchasedtickets}} (ticketId) ... done (time: 0.001s)
    > create index events_purchasedtickets_orderId_idx on {{%events_purchasedtickets}} (orderId) ... done (time: 0.002s)
    > create index events_purchasedtickets_lineItemId_idx on {{%events_purchasedtickets}} (lineItemId) ... done (time: 0.002s)
    > create unique index events_tickets_sku_unq_idx on {{%events_tickets}} (sku) ... done (time: 0.001s)
    > create index events_tickets_eventId_idx on {{%events_tickets}} (eventId) ... done (time: 0.001s)
    > create index events_tickets_ticketTypeId_idx on {{%events_tickets}} (ticketTypeId) ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'ticketTypeId' doesn't exist in table
The SQL being executed was: ALTER TABLE `events_tickets` ADD INDEX `events_tickets_ticketTypeId_idx` (`ticketTypeId`) (/sites/test/site/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /sites/test/site/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `ev...')
#1 /sites/test/site/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('ALTER TABLE `ev...')
#2 /sites/test/site/vendor/yiisoft/yii2/db/Migration.php(495): yii\db\Command->execute()
#3 /sites/test/site/vendor/craftcms/cms/src/db/Migration.php(400): yii\db\Migration->createIndex('events_tickets_...', '{{%events_ticke...', 'ticketTypeId', false)
#4 /sites/test/site/vendor/verbb/events/src/migrations/Install.php(140): craft\db\Migration->createIndex('events_tickets_...', '{{%events_ticke...', 'ticketTypeId', false)
#5 /sites/test/site/vendor/verbb/events/src/migrations/Install.php(16): verbb\events\migrations\Install->createIndexes()
#6 /sites/test/site/vendor/craftcms/cms/src/db/Migration.php(56): verbb\events\migrations\Install->safeUp()
#7 /sites/test/site/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#8 /sites/test/site/vendor/craftcms/cms/src/base/Plugin.php(152): craft\db\MigrationManager->migrateUp(Object(verbb\events\migrations\Install))
#9 /sites/test/site/vendor/craftcms/cms/src/services/Plugins.php(520): craft\base\Plugin->install()
#10 /sites/test/site/vendor/craftcms/cms/src/controllers/PluginsController.php(51): craft\services\Plugins->installPlugin('events', 'standard')
#11 [internal function]: craft\controllers\PluginsController->actionInstallPlugin()
#12 /sites/test/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /sites/test/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /sites/test/site/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('install-plugin', Array)
#15 /sites/test/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('install-plugin', Array)
#16 /sites/test/site/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('plugins/install...', Array)
#17 /sites/test/site/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('plugins/install...', Array)
#18 /sites/test/site/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#19 /sites/test/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /sites/test/site/web/index.php(41): yii\base\Application->run()
#21 {main}

2019-04-23 16:22:21 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2019-04-23 16:22:21 [-][1][-][info][yii\db\Command::execute] DELETE FROM `plugins` WHERE `handle`='events'
2019-04-23 16:22:21 [-][1][-][profile begin][yii\db\Command::execute] DELETE FROM `plugins` WHERE `handle`='events'
2019-04-23 16:22:21 [-][1][-][profile end][yii\db\Command::execute] DELETE FROM `plugins` WHERE `handle`='events'
2019-04-23 16:22:21 [-][1][-][info][application] $_GET = []

$_POST = [
    'pluginHandle' => 'events'
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'action' => 'plugins/install-plugin'
]

$_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => [
        'error' => -1
    ]
    'bd62416aa8538ede709019a5e113eea5__auth_access' => [
        0 => 'saveAssetInVolume:23'
        1 => 'saveAssetInVolume:1'
        2 => 'saveAssetInVolume:24'
        3 => 'saveAssetInVolume:4'
        4 => 'saveAssetInVolume:3'
    ]
    '1031b8c41dfff97a311a7ac99863bdc5__token' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    '1031b8c41dfff97a311a7ac99863bdc5__id' => '1'
    '1031b8c41dfff97a311a7ac99863bdc5__expire' => 4743346941
    'error' => 'Couldn’t install plugin.'
]
```

**Comment by engram-design** [comment]
Sorry about that, should be fixed in [1.0.1](https://github.com/verbb/events/releases/tag/1.0.1)

**Comment by jacobgraf** [comment]
Still getting the error in 1.0.1. 😢

Craft Solo 3.1.24
Craft Commerce 2.1.3.1

**Comment by mikestecker** [comment]
@engram-design Yeah, I'm having a different error with 1.0.1

Looks like it never fully removed itself when it failed in 1.0.0: `Base table or view already exists: 1050 Table 'events_events' already exists`


@jacobgraf I had to manually delete the following tables in order to have a successful install:
`events_events`
`events_eventtypes`
`events_eventtypes_sites`
`events_purchasedtickets`
`events_tickets`
`events_tickettypes`



@engram-design here are the full logs:
```
2019-04-24 11:37:50 [-][1][-][trace][yii\base\Controller::runAction] Route to run: plugins/install-plugin
2019-04-24 11:37:50 [-][1][-][trace][yii\base\InlineAction::runWithParams] Running action: craft\controllers\PluginsController::actionInstallPlugin()
2019-04-24 11:37:50 [-][1][-][info][yii\db\Command::query] SELECT `id`, `handle`, `version`, `schemaVersion`, `licenseKeyStatus`, `installDate`, `licensedEdition`
FROM `plugins`
WHERE `handle`='events'
LIMIT 1
2019-04-24 11:37:50 [-][1][-][profile begin][yii\db\Command::query] SELECT `id`, `handle`, `version`, `schemaVersion`, `licenseKeyStatus`, `installDate`, `licensedEdition`
FROM `plugins`
WHERE `handle`='events'
LIMIT 1
2019-04-24 11:37:50 [-][1][-][profile end][yii\db\Command::query] SELECT `id`, `handle`, `version`, `schemaVersion`, `licenseKeyStatus`, `installDate`, `licensedEdition`
FROM `plugins`
WHERE `handle`='events'
LIMIT 1
2019-04-24 11:37:50 [-][1][-][trace][yii\db\Transaction::begin] Begin transaction
2019-04-24 11:37:50 [-][1][-][info][yii\db\Command::query] SHOW FULL COLUMNS FROM `plugins`
2019-04-24 11:37:50 [-][1][-][profile begin][yii\db\Command::query] SHOW FULL COLUMNS FROM `plugins`
2019-04-24 11:37:50 [-][1][-][profile end][yii\db\Command::query] SHOW FULL COLUMNS FROM `plugins`
2019-04-24 11:37:50 [-][1][-][info][yii\db\Command::query] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'plugins' AND kcu.table_name = 'plugins'
2019-04-24 11:37:50 [-][1][-][profile begin][yii\db\Command::query] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'plugins' AND kcu.table_name = 'plugins'
2019-04-24 11:37:50 [-][1][-][profile end][yii\db\Command::query] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'plugins' AND kcu.table_name = 'plugins'
2019-04-24 11:37:50 [-][1][-][info][yii\db\Command::query] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name,
    rc.UPDATE_RULE,
    rc.DELETE_RULE
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'plugins' AND kcu.table_name = 'plugins'
2019-04-24 11:37:50 [-][1][-][profile begin][yii\db\Command::query] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name,
    rc.UPDATE_RULE,
    rc.DELETE_RULE
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'plugins' AND kcu.table_name = 'plugins'
2019-04-24 11:37:50 [-][1][-][profile end][yii\db\Command::query] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name,
    rc.UPDATE_RULE,
    rc.DELETE_RULE
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'plugins' AND kcu.table_name = 'plugins'
2019-04-24 11:37:50 [-][1][-][info][yii\db\Command::execute] INSERT INTO `plugins` (`handle`, `version`, `schemaVersion`, `installDate`, `dateCreated`, `dateUpdated`, `uid`) VALUES ('events', '1.0.1', '1.0.0', '2019-04-24 15:37:50', '2019-04-24 15:37:50', '2019-04-24 15:37:50', 'ec060bab-0461-476b-90cb-53f3c0dafe26')
2019-04-24 11:37:50 [-][1][-][profile begin][yii\db\Command::execute] INSERT INTO `plugins` (`handle`, `version`, `schemaVersion`, `installDate`, `dateCreated`, `dateUpdated`, `uid`) VALUES ('events', '1.0.1', '1.0.0', '2019-04-24 15:37:50', '2019-04-24 15:37:50', '2019-04-24 15:37:50', 'ec060bab-0461-476b-90cb-53f3c0dafe26')
2019-04-24 11:37:50 [-][1][-][profile end][yii\db\Command::execute] INSERT INTO `plugins` (`handle`, `version`, `schemaVersion`, `installDate`, `dateCreated`, `dateUpdated`, `uid`) VALUES ('events', '1.0.1', '1.0.0', '2019-04-24 15:37:50', '2019-04-24 15:37:50', '2019-04-24 15:37:50', 'ec060bab-0461-476b-90cb-53f3c0dafe26')
2019-04-24 11:37:50 [-][1][-][info][craft\db\MigrationManager::migrateUp] Applying Install
2019-04-24 11:37:50 [-][1][-][trace][yii\db\Transaction::begin] Set savepoint 1
2019-04-24 11:37:50 [-][1][-][info][yii\db\Command::execute] SAVEPOINT LEVEL1
2019-04-24 11:37:50 [-][1][-][profile begin][yii\db\Command::execute] SAVEPOINT LEVEL1
2019-04-24 11:37:50 [-][1][-][profile end][yii\db\Command::execute] SAVEPOINT LEVEL1
2019-04-24 11:37:50 [-][1][-][info][yii\db\Command::execute] CREATE TABLE `events_events` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`typeId` int(11),
	`allDay` tinyint(1),
	`capacity` int(11),
	`startDate` datetime,
	`endDate` datetime,
	`postDate` datetime,
	`expiryDate` datetime,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-24 11:37:50 [-][1][-][profile begin][yii\db\Command::execute] CREATE TABLE `events_events` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`typeId` int(11),
	`allDay` tinyint(1),
	`capacity` int(11),
	`startDate` datetime,
	`endDate` datetime,
	`postDate` datetime,
	`expiryDate` datetime,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-24 11:37:50 [-][1][-][profile end][yii\db\Command::execute] CREATE TABLE `events_events` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`typeId` int(11),
	`allDay` tinyint(1),
	`capacity` int(11),
	`startDate` datetime,
	`endDate` datetime,
	`postDate` datetime,
	`expiryDate` datetime,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
2019-04-24 11:37:50 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back to savepoint 1
2019-04-24 11:37:50 [-][1][-][info][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2019-04-24 11:37:50 [-][1][-][profile begin][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2019-04-24 11:37:50 [-][1][-][profile end][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2019-04-24 11:37:50 [-][1][-][warning][craft\db\mysql\Schema::rollBackSavepoint] Tried to roll back a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: ROLLBACK TO SAVEPOINT LEVEL1
2019-04-24 11:37:50 [-][1][-][error][craft\db\MigrationManager::migrateUp] Failed to apply Install (time: 0.001s). Output:
    > create table {{%events_events}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'events_events' already exists
The SQL being executed was: CREATE TABLE `events_events` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`typeId` int(11),
	`allDay` tinyint(1),
	`capacity` int(11),
	`startDate` datetime,
	`endDate` datetime,
	`postDate` datetime,
	`expiryDate` datetime,
	`dateCreated` datetime NOT NULL,
	`dateUpdated` datetime NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8 (/sites/test/site/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /sites/test/site/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `e...')
#1 /sites/test/site/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('CREATE TABLE `e...')
#2 /sites/test/site/vendor/yiisoft/yii2/db/Migration.php(323): yii\db\Command->execute()
#3 /sites/test/site/vendor/verbb/events/src/migrations/Install.php(46): yii\db\Migration->createTable('{{%events_event...', Array)
#4 /sites/test/site/vendor/verbb/events/src/migrations/Install.php(15): verbb\events\migrations\Install->createTables()
#5 /sites/test/site/vendor/craftcms/cms/src/db/Migration.php(56): verbb\events\migrations\Install->safeUp()
#6 /sites/test/site/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#7 /sites/test/site/vendor/craftcms/cms/src/base/Plugin.php(152): craft\db\MigrationManager->migrateUp(Object(verbb\events\migrations\Install))
#8 /sites/test/site/vendor/craftcms/cms/src/services/Plugins.php(520): craft\base\Plugin->install()
#9 /sites/test/site/vendor/craftcms/cms/src/controllers/PluginsController.php(51): craft\services\Plugins->installPlugin('events', 'standard')
#10 [internal function]: craft\controllers\PluginsController->actionInstallPlugin()
#11 /sites/test/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /sites/test/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /sites/test/site/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('install-plugin', Array)
#14 /sites/test/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('install-plugin', Array)
#15 /sites/test/site/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('plugins/install...', Array)
#16 /sites/test/site/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('plugins/install...', Array)
#17 /sites/test/site/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 /sites/test/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /sites/test/site/web/index.php(41): yii\base\Application->run()
#20 /Users/mikestecker/.composer/vendor/laravel/valet/server.php(151): require('/Users/mikestec...')
#21 {main}

2019-04-24 11:37:50 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2019-04-24 11:37:50 [-][1][-][info][yii\db\Command::execute] DELETE FROM `plugins` WHERE `handle`='events'
2019-04-24 11:37:50 [-][1][-][profile begin][yii\db\Command::execute] DELETE FROM `plugins` WHERE `handle`='events'
2019-04-24 11:37:50 [-][1][-][profile end][yii\db\Command::execute] DELETE FROM `plugins` WHERE `handle`='events'
2019-04-24 11:37:50 [-][1][-][info][application] $_GET = []

$_POST = [
    'pluginHandle' => 'events'
    'CRAFT_CSRF_TOKEN' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'action' => 'plugins/install-plugin'
]

$_FILES = []

$_COOKIE = [
    '1031b8c41dfff97a311a7ac99863bdc5_username' => '744fc5db316d0236a63ceb9c1a5c1e5e0b0ed5f49f6b964bf82ea59183e46556a:2:{i:0;s:41:\"1031b8c41dfff97a311a7ac99863bdc5_username\";i:1;s:15:\"mike@stecker.me\";}'
    '__stripe_mid' => 'd62a6a5f-caab-4682-9405-3700bd12f0f0'
    'CRAFT_CSRF_TOKEN' => '•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    'CraftSessionId' => 'a4euoebka9k7fb175voucv3bqn'
    '1031b8c41dfff97a311a7ac99863bdc5_identity' => 'd9f14f28d6af2e2a832e22b75d3a84b0ff77e611b084f051848af444bac82fe5a:2:{i:0;s:41:\"1031b8c41dfff97a311a7ac99863bdc5_identity\";i:1;s:256:\"[\"1\",\"[\\\"uJ5YD5iHTnl4Wt3N8QR24H3w1fANFomOCi7_y2FgtopUJ0JiZFC_Lwy6JMtwvsgfnkmyxm_BxSyNQ5OFwxcflR1ikWyHPOWwOrJS\\\",null,\\\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36\\\"]\",3187296000]\";}'
]

$_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => [
        'error' => -1
    ]
    'bd62416aa8538ede709019a5e113eea5__auth_access' => [
        0 => 'saveAssetInVolume:23'
        1 => 'saveAssetInVolume:1'
        2 => 'saveAssetInVolume:24'
        3 => 'saveAssetInVolume:4'
        4 => 'saveAssetInVolume:3'
    ]
    '1031b8c41dfff97a311a7ac99863bdc5__token' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    '1031b8c41dfff97a311a7ac99863bdc5__id' => '1'
    '1031b8c41dfff97a311a7ac99863bdc5__expire' => 4743416270
    'error' => 'Couldn’t install plugin.'
]
```

**Comment by jacobgraf** [comment]
@mikestecker You da man! Deleted those tables and it successfully installed. Thanks!

**Comment by mikestecker** [comment]
@bartrylant see my latest comment for the fix since you also had a failed 1.0.0

**Comment by engram-design** [comment]
@mikestecker Yep, sorry about that - my fault for a last minute change with the database structure. I actually thought it would bail on creating those tables if there was an error, as part of the migration process (if there's an error, roll-back changes), but that seems to not be the case.

Sorry for the inconvenience everyone!

**Comment by peteeveleigh** [comment]
I'm getting this issue with v1.1.6 of the plugin and attempting to install into Craft 3.3.7 Pro (currently on trial)
The db tables are created but the plugin doesn't install.
Removing the plugin doesn't remove the tables.

Manually deleting the tables doesn't help fix the problem. 

There's quite a lot in the logs but the standouts seem to be

```
2019-11-05 01:19:22 [-][1][-][warning][craft\db\mysql\Schema::rollBackSavepoint] Tried to roll back a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: ROLLBACK TO SAVEPOINT LEVEL1
2019-11-05 01:19:22 [-][1][-][error][craft\db\MigrationManager::migrateUp] Failed to apply Install (time: 0.553s). Output:
    > create table {{%events_events}} ... done (time: 0.032s)
    > create table {{%events_eventtypes}} ... done (time: 0.018s)
    > create table {{%events_eventtypes_sites}} ... done (time: 0.016s)
    > create table {{%events_tickets}} ... done (time: 0.015s)
    > create table {{%events_tickettypes}} ... done (time: 0.016s)
    > create table {{%events_purchasedtickets}} ... done (time: 0.016s)
    > create index events_events_typeId_idx on {{%events_events}} (typeId) ... done (time: 0.017s)
    > create unique index events_eventtypes_handle_unq_idx on {{%events_eventtypes}} (handle) ... done (time: 0.017s)
    > create index events_eventtypes_fieldLayoutId_idx on {{%events_eventtypes}} (fieldLayoutId) ... done (time: 0.023s)
    > create unique index events_eventtypes_sites_eventTypeId_siteId_unq_idx on {{%events_eventtypes_sites}} (eventTypeId,siteId) ... done (time: 0.019s)
    > create index events_eventtypes_sites_siteId_idx on {{%events_eventtypes_sites}} (siteId) ... done (time: 0.018s)
    > create index events_purchasedtickets_eventId_idx on {{%events_purchasedtickets}} (eventId) ... done (time: 0.017s)
    > create index events_purchasedtickets_ticketId_idx on {{%events_purchasedtickets}} (ticketId) ... done (time: 0.018s)
    > create index events_purchasedtickets_orderId_idx on {{%events_purchasedtickets}} (orderId) ... done (time: 0.015s)
    > create index events_purchasedtickets_lineItemId_idx on {{%events_purchasedtickets}} (lineItemId) ... done (time: 0.018s)
    > create unique index events_tickets_sku_unq_idx on {{%events_tickets}} (sku) ... done (time: 0.017s)
    > create index events_tickets_eventId_idx on {{%events_tickets}} (eventId) ... done (time: 0.015s)
    > create index events_tickets_typeId_idx on {{%events_tickets}} (typeId) ... done (time: 0.019s)
    > create unique index events_tickettypes_handle_unq_idx on {{%events_tickettypes}} (handle) ... done (time: 0.018s)
    > create index events_tickettypes_taxCategoryId_idx on {{%events_tickettypes}} (taxCategoryId) ... done (time: 0.016s)
    > create index events_tickettypes_shippingCategoryId_idx on {{%events_tickettypes}} (shippingCategoryId) ... done (time: 0.017s)
    > create index events_tickettypes_fieldLayoutId_idx on {{%events_tickettypes}} (fieldLayoutId) ... done (time: 0.017s)
    > add foreign key events_events_id_fk: {{%events_events}} (id) references {{%elements}} (id) ... done (time: 0.021s)
    > add foreign key events_events_typeId_fk: {{%events_events}} (typeId) references {{%events_eventtypes}} (id) ... done (time: 0.023s)
    > add foreign key events_eventtypes_fieldLayoutId_fk: {{%events_eventtypes}} (fieldLayoutId) references {{%fieldlayouts}} (id) ... done (time: 0.022s)
    > add foreign key events_eventtypes_sites_eventTypeId_fk: {{%events_eventtypes_sites}} (eventTypeId) references {{%events_eventtypes}} (id) ... done (time: 0.022s)
    > add foreign key events_eventtypes_sites_siteId_fk: {{%events_eventtypes_sites}} (siteId) references {{%sites}} (id) ... done (time: 0.023s)
    > add foreign key events_purchasedtickets_eventId_fk: {{%events_purchasedtickets}} (eventId) references {{%events_events}} (id) ... done (time: 0.022s)
    > add foreign key events_purchasedtickets_lineItemId_fk: {{%events_purchasedtickets}} (lineItemId) references {{%commerce_lineitems}} (id) ...Exception: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint
The SQL being executed was: ALTER TABLE `events_purchasedtickets` ADD CONSTRAINT `events_purchasedtickets_lineItemId_fk` FOREIGN KEY (`lineItemId`) REFERENCES `commerce_lineitems` (`id`) ON DELETE SET NULL (/Users/pete/Projects/FantasticMachine/pcn/dev/build/vendor/yiisoft/yii2/db/Schema.php:664)
```

**Comment by engram-design** [comment]
@fantasticmachine Do you have Commerce installed? I think this error might appear when you try to install the plugin without Commerce installed first?

**Comment by fantasticmachine** [comment]
Hi @engram-design 

That was it. Commerce wasn't installed 🤦‍♂ 

I installed Commerce and tried again. Still no luck. 
Removed Events. And Reinstalled. No luck.
Removed Events. Checked the database and could see the tables still there so removed them manually. Reinstalled and.... WIN!

Can't believe I didn't realise that's what was wrong. 

Many thanks
