### ISSUE TITLE
Overbooking is possible

### ISSUE THREAD

**Issue by mihob** [verbb/Events#129]
### Describe the bug

It is possible to buy any number of tickets as long as an event is not fully booked.

For example, if an event has 10 seats, it is possible to buy 100 tickets.

It should not be possible to add more tickets to the shopping basket than are available.

The same problem exists on a ticket basis

### Steps to reproduce

1.  For example, set the capacity limit of an event or a ticket to 10 
2. Add 20 tickets to the shopping basket
3. Finalise the purchase

### Craft CMS version

Craft Pro 4.5.11.1

### Plugin version

2.0.2

### Multi-site?

Yes

**Comment by engram-design** [comment]
Not seeing that, sorry. I'm getting the message "You reached the maximum ticket quantity for Test Event" whenever I try and add more tickets to my cart than are available for the event. This should be controlled through [here](https://github.com/verbb/events/blob/89a4627ab6ad1b7799f489164def0b089e9587e3/src/elements/Ticket.php#L430)

**Comment by mihob** [comment]
I think the problem is that we don't add a ticket with a quantity of 10, but the ticket 10 times as a single item (each with a unique hash hidden in the option array).

We do this because we have to query the first name and surname for each individual ticket and therefore need individual line items.

You don't seem to be looking at the total quantity that is added to the shopping basket.

**Comment by engram-design** [comment]
Gotcha. Yes, when singular line items are added this will be an issue. Normally, even if you add a ticket one at a time, they are combined into a single line item with multiple quantity set. 

Fixed for the next release. To get this early, run `composer require verbb/events:"dev-craft-4 as 2.0.2"`.

I should also note that the plugin doesn't provide a 100% bullet-proof overbooking protection mechanism. For one, there's no reserve system, so technically if multiple people checkout at the same time, there's the potential for tickets to be purchased at the same time, over the limit. There's also no reservation on "stock" when adding to the cart, so one user might've added all remaining tickets to the cart (but not purchased) and another user does the same, and whoever checks out first gets the tickets.

**Comment by engram-design** [comment]
Should be fixed in [2.0.3](https://github.com/verbb/events/releases/tag/2.0.3)

**Comment by mihob** [comment]
@engram-design If I see it correctly, the problem is back with version 3.0

**Comment by engram-design** [comment]
@mihob I can't add items to my cart if it's over the threshold of capacity in [3.0.4](https://github.com/verbb/events/releases/tag/3.0.4).

For example, I set my ticket type capacity to 10, and try and add 11 tickets to my cart, I get an error message:

```
Unable to update cart. lineItems.0.qty: There are only 10 “My Event - 28/12/2024 1:00 pm — 2:00 pm” items left in stock.
```

If I set the Event Capacity to 5, which overrides ticket type capacity, then I get the same error message.

If I add one item at a time, as I commented, I still reach that error message.

**Comment by mihob** [comment]
@engram-design 

Hmm 

I get the error message when I try to add them all at once.

But if I add the tickets individually, I can add as many as I want.

Can you tell me where this is checked in the code? This seems to have changed in version 3

**Comment by engram-design** [comment]
Strange! I did ensure to test both methods just in case. Can you let me know your updates event setup for Events 3, just so we're on the same page?

It should be all routed through [`$ticket->getIsAvailable()`](https://github.com/verbb/events/blob/ed2f9a8f9e7a176c1ba5a77c9f7d2a5abf665c99/src/elements/Ticket.php#L312)

**Comment by mihob** [comment]
Sorry for my late reply, I will check again
